<?php

namespace QuickDns\Tests;

use QuickDns\Group;
use QuickDns\QuickDns;
use QuickDns\Template;

class TestCase extends \PHPUnit\Framework\TestCase
{
    protected QuickDns $quickDns;

    protected $apiEmail;

    protected $apiPassword;

    protected $testGroup = 'test-group'; // Need to exist before running tests

    protected $testTemplate = 'test-template';  // Need to exist before running tests

    protected $testDomain = 'quickdns-api-test-domain.dk';

    protected function setUp(): void
    {
        parent::setUp();

        $this->quickDns = new QuickDns(getenv('QUICKDNS_EMAIL'), getenv('QUICKDNS_PASSWORD'));
    }

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();

        if (! getenv('QUICKDNS_EMAIL') || ! getenv('QUICKDNS_PASSWORD')) {
            throw new \Exception('ENV variables is not set. See documentation,.');
        }

        $quickDns = new QuickDns(getenv('QUICKDNS_EMAIL'), getenv('QUICKDNS_PASSWORD'));

        foreach ($quickDns->getGroups() as $group) {
            if ($group->name === 'test-group') {
                $group->delete();
            }
        }
        (new Group($quickDns, 'test-group'))->create();

        foreach ($quickDns->getTemplates() as $template) {
            if ($template->name === 'test-template') {
                $template->delete();
            }
        }
        (new Template($quickDns, 'test-template'))->create();
    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}
